name: esperimento-ocr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dlib
  - pip
  - pip:
      # Web app
      - streamlit==1.47.0

      # Computer Vision / Imaging
      - opencv-python-headless==4.8.1.78
      - Pillow==10.3.0
      - pillow-heif==0.13.1
      - numpy

      # OCR / Text detection
      - easyocr==1.7.1
      - pytesseract
      - craft-text-detector
      - keras-ocr

      # Deep learning (CPU)
      - torch==2.0.1
      - torchvision==0.15.2

      # Utils (alcune sono dipendenze comuni di OCR)
      - scipy==1.10.1
      - imutils==0.5.4
      - shapely==2.0.4
      - networkx==3.1
      - scikit-image==0.21.0
      - python-bidi==0.4.2
      - PyYAML==6.0.1
      - pyclipper==1.3.0.post5

      # Visualizzazione (usata nei file .py)
      - matplotlib
